// Generated by CoffeeScript 1.4.0

/*
API Facade client
*/


(function() {
  var ApiFacadeClient;

  ApiFacadeClient = require('./api-facade-client');

  module.exports = {
    ApiFacadeClient: ApiFacadeClient,
    client: function(settings) {
      if (settings == null) {
        settings = {};
      }
      return new ApiFacadeClient(settings);
    }
  };

}).call(this);
